import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {newRun} from '../js/core/game.js';
import {exportSave} from '../js/persistence/run-store.js';
import {defaultMeta} from '../js/persistence/meta-store.js';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const evidence=path.join(root,'evidence');fs.mkdirSync(evidence,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.webmanifest':'application/manifest+json','.json':'application/json'};
const server=http.createServer((req,res)=>{
 let pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
 if(!pathname.startsWith('/test-subpath/')){res.writeHead(404);return res.end();}
 pathname=pathname.slice('/test-subpath/'.length)||'index.html';
 const file=path.resolve(root,pathname);
 if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}
 res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream','cache-control':'no-cache'});fs.createReadStream(file).pipe(res);
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${server.address().port}/test-subpath/`;
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});
const results=[],errors=[];
const check=async(name,fn)=>{await fn();results.push({name,result:'PASS'});console.log('PASS',name);};
function observe(p){p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});}
async function ready(p,url){await p.goto(url);await p.waitForSelector('body[data-ready="true"]');await p.waitForFunction(()=>!document.querySelector('#message').textContent.startsWith('Inicializando'));}
const ctx=await browser.newContext({viewport:{width:1440,height:1100}}),p=await ctx.newPage();observe(p);
async function imp(s){await p.locator('#importSaveInput').setInputFiles({name:'fixture.json',mimeType:'application/json',buffer:Buffer.from(exportSave(s,defaultMeta()))});await p.waitForFunction(seed=>document.querySelector('#seedValue').textContent===seed,s.seed);}
async function click(selector){await p.locator(selector).click();}
try{
 await ready(p,base);
 await check('HTTP subruta: arranque con 8 cartas',async()=>assert.equal(await p.locator('.card').count(),8));
 await check('Nueva expedición: cambia semilla y mano',async()=>{const seed=await p.locator('#seedValue').textContent(),cards=await p.locator('#hand').textContent();await click('#newRunBtn');assert.notEqual(await p.locator('#seedValue').textContent(),seed);assert.notEqual(await p.locator('#hand').textContent(),cards);});
 await check('Semilla escrita y repetir semilla',async()=>{await p.locator('#seedInput').fill('REPRO-404');await click('#newRunBtn');const cards=await p.locator('#hand').textContent();assert.equal(await p.locator('#seedValue').textContent(),'REPRO-404');await click('#repeatSeedBtn');assert.equal(await p.locator('#hand').textContent(),cards);});
 await check('Seleccionar/deseleccionar carta por ratón',async()=>{await click('.card:first-child');assert.equal(await p.locator('.card[aria-pressed="true"]').count(),1);await click('.card:first-child');assert.equal(await p.locator('.card[aria-pressed="true"]').count(),0);});
 await check('Teclado Space/Enter conserva foco en carta',async()=>{await p.locator('.card').first().focus();await p.keyboard.press('Space');assert.equal(await p.locator('.card:focus').count(),1);await p.keyboard.press('Enter');assert.equal(await p.locator('.card[aria-pressed="true"]').count(),0);});
 await check('Jugar mano: puntos y contador',async()=>{await click('.card:first-child');await click('#playBtn');assert.equal(await p.locator('#handsLeft').textContent(),'3');assert.ok(Number(await p.locator('#totalScore').textContent())>0);});
 await check('Descartar: contador y reposición',async()=>{await click('.card:first-child');await click('#discardBtn');assert.equal(await p.locator('#discardsLeft').textContent(),'4');assert.equal(await p.locator('.card').count(),8);});
 await check('Códice abre y cierra visualmente',async()=>{assert.equal(await p.locator('#metaPanel').isVisible(),false);await click('#codexBtn');assert.equal(await p.locator('#metaPanel').isVisible(),true);await click('#codexBtn');assert.equal(await p.locator('#metaPanel').isVisible(),false);});
 await check('Audio ON/OFF',async()=>{await click('#audioBtn');await p.waitForFunction(()=>document.querySelector('#audioBtn').getAttribute('aria-pressed')==='true');await click('#audioBtn');await p.waitForFunction(()=>document.querySelector('#audioBtn').getAttribute('aria-pressed')==='false');});
 await check('CRT ON/OFF',async()=>{await click('#fxBtn');assert.equal(await p.locator('body').getAttribute('data-fx'),'off');await click('#fxBtn');assert.equal(await p.locator('body').getAttribute('data-fx'),'on');});
 let exported;
 await check('Exportar: descarga real JSON',async()=>{const wait=p.waitForEvent('download');await click('#exportSaveBtn');const dl=await wait;exported=fs.readFileSync(await dl.path());assert.equal(JSON.parse(exported).format,'abyssal-hand-404-save');});
 await check('Importar: selector real y restauración',async()=>{await click('#newRunBtn');const wait=p.waitForEvent('filechooser');await click('#importSaveBtn');await (await wait).setFiles({name:'run.json',mimeType:'application/json',buffer:exported});await p.waitForFunction(()=>document.querySelector('#seedValue').textContent==='REPRO-404');assert.equal(await p.locator('#handsLeft').textContent(),'3');});
 await check('Continuar autosave + recarga',async()=>{await click('#continueRunBtn');await p.waitForFunction(()=>document.querySelector('#message').textContent.startsWith('Expedición recuperada'));await ready(p,base);assert.equal(await p.locator('#seedValue').textContent(),'REPRO-404');assert.equal(await p.locator('#handsLeft').textContent(),'3');});
 await check('Importación inválida preserva partida',async()=>{await p.locator('#importSaveInput').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await p.waitForFunction(()=>document.querySelector('#message').textContent.includes('No se pudo importar'));assert.equal(await p.locator('#seedValue').textContent(),'REPRO-404');});
 await check('Recompensa y ruta de combate',async()=>{const s=newRun('REWARD');s.screenMode='reward';s.status='choice';s.pendingReward=20;await imp(s);await click('[data-action="claim"]');assert.equal(await p.locator('#echoesValue').textContent(),'20');await click('[data-action="route"][data-value$="battle"]');assert.equal(await p.locator('#encounterValue').textContent(),'2');});
 await check('Ruta mercado, comprar, duplicado, salir',async()=>{const s=newRun('SHOP');s.screenMode='route';s.status='choice';s.echoes=100;s.routeOptions=[{id:'s',type:'shop',name:'MERCADO',icon:'¤'}];await imp(s);await click('[data-action="route"]');await click('[data-action="buy"][data-value="bone-die"]');const money=await p.locator('#echoesValue').textContent();await click('[data-action="buy"][data-value="bone-die"]');assert.equal(await p.locator('#echoesValue').textContent(),money);await click('[data-action="continue"]');assert.equal(await p.locator('#encounterValue').textContent(),'2');});
 await check('Aceptar pacto',async()=>{const s=newRun('PACT');s.screenMode='ritual';s.status='choice';await imp(s);await click('[data-action="pact"][data-value="blood-pact"]');assert.ok((await p.locator('#powers').textContent()).includes('SANGRE'));assert.equal(await p.locator('#encounterValue').textContent(),'2');});
 await check('Rechazar pacto y continuar',async()=>{const s=newRun('REJECT');s.screenMode='ritual';s.status='choice';await imp(s);await click('[data-action="continue"]');assert.equal(await p.locator('#encounterValue').textContent(),'2');});
 for(const choice of ['open','ignore'])await check('Evento '+choice,async()=>{const s=newRun('EVENT-'+choice);s.screenMode='event';s.status='choice';s.madness=20;await imp(s);await click(`[data-action="event"][data-value="${choice}"]`);assert.equal(await p.locator('#madnessValue').textContent(),choice==='open'?'32%':'15%');assert.equal(await p.locator('#encounterValue').textContent(),'2');});
 await check('Cada botón de ritual consume el correcto',async()=>{const s=newRun('RITUAL');s.madness=40;s.rituals=[{id:'salt-circle',name:'SAL'},{id:'red-key',name:'LLAVE'}];await imp(s);await click('[data-ritual-id="red-key"]');assert.equal(await p.locator('#madnessValue').textContent(),'40%');assert.equal(await p.locator('[data-ritual-id="salt-circle"]').count(),1);await click('[data-ritual-id="salt-circle"]');assert.equal(await p.locator('#madnessValue').textContent(),'22%');});
 await check('Rey Sin Rostro: jugar, guardar y recuperar',async()=>{const s=newRun('KING');s.encounter=9;await imp(s);await click('.card:first-child');await click('#playBtn');await click('#continueRunBtn');await p.waitForFunction(()=>document.querySelector('#message').textContent.startsWith('Expedición recuperada'));assert.equal(await p.locator('#encounterValue').textContent(),'9');assert.equal(await p.locator('#handsLeft').textContent(),'3');});
 await check('8 fondos decodifican + retratos de jefes',async()=>{const seen=new Set();for(let z=0;z<8;z++){const s=newRun('SECTOR-'+z);s.encounter=(z+1)*3;await imp(s);const url=await p.locator('.table').evaluate(el=>el.style.getPropertyValue('--sector-image').slice(5,-2));assert.equal(await p.evaluate(src=>new Promise(r=>{const im=new Image();im.onload=()=>r(im.naturalWidth>0);im.onerror=()=>r(false);im.src=src;}),url),true);seen.add(url);await p.waitForFunction(()=>document.querySelector('.boss-portrait')?.naturalWidth>0);}assert.equal(seen.size,8);});
 await check('Victoria y nueva expedición',async()=>{const s=newRun('WIN');s.encounter=24;s.screenMode='reward';s.status='choice';s.pendingReward=80;await imp(s);await click('[data-action="claim"]');assert.equal(await p.locator('.victory-mark').count(),1);await click('#newRunBtn');assert.equal(await p.locator('#encounterValue').textContent(),'1');assert.equal(await p.locator('#nodePanel').isVisible(),false);});
 await p.screenshot({path:path.join(evidence,'desktop.png'),fullPage:true});
 await check('Offline: recarga y jugar con SW real',async()=>{await p.evaluate(()=>navigator.serviceWorker.ready);await p.reload();await p.waitForFunction(()=>!!navigator.serviceWorker.controller);await ctx.setOffline(true);await p.goto(base+'?offline-probe=1');await p.waitForSelector('.card');await click('#newRunBtn');await click('.card:first-child');await click('#playBtn');assert.equal(await p.locator('#handsLeft').textContent(),'3');await ctx.setOffline(false);});
 await check('Móvil 390px: botones, cartas y sin desborde',async()=>{const m=await ctx.newPage();await m.setViewportSize({width:390,height:844});observe(m);await ready(m,base);await m.locator('#newRunBtn').click();await m.locator('.card').last().click();await m.locator('#playBtn').click();assert.equal(await m.locator('#handsLeft').textContent(),'3');assert.equal(await m.evaluate(()=>innerWidth),390);assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await m.screenshot({path:path.join(evidence,'mobile.png'),fullPage:true});await m.close();});
 await check('file://: nueva, jugar, descartar y códice',async()=>{const f=await ctx.newPage();observe(f);await ready(f,pathToFileURL(path.join(root,'index.html')).href);const seed=await f.locator('#seedValue').textContent();await f.locator('#newRunBtn').click();assert.notEqual(await f.locator('#seedValue').textContent(),seed);await f.locator('.card').first().click();await f.locator('#playBtn').click();assert.equal(await f.locator('#handsLeft').textContent(),'3');await f.locator('.card').first().click();await f.locator('#discardBtn').click();assert.equal(await f.locator('#discardsLeft').textContent(),'4');await f.locator('#codexBtn').click();assert.equal(await f.locator('#metaPanel').isVisible(),true);await f.close();});
 await check('IDB bloqueado: clic temprano no se pierde al acabar boot',async()=>{const c=await browser.newContext();await c.addInitScript(()=>{Object.defineProperty(window,'indexedDB',{value:{open(){return {}}}});});const q=await c.newPage();observe(q);await q.goto(base);await q.waitForSelector('.card');await q.locator('#newRunBtn').click();const seed=await q.locator('#seedValue').textContent();await q.locator('.card').first().click();await q.locator('#playBtn').click();await q.waitForTimeout(2300);assert.equal(await q.locator('#seedValue').textContent(),seed);assert.equal(await q.locator('#handsLeft').textContent(),'3');await c.close();});
 await check('Storage denegado: controles operativos',async()=>{const c=await browser.newContext();await c.addInitScript(()=>{for(const key of ['localStorage','indexedDB'])Object.defineProperty(window,key,{get(){throw new DOMException('Blocked','SecurityError')}});});const q=await c.newPage();observe(q);await ready(q,base);await q.locator('#newRunBtn').click();await q.locator('.card').first().click();await q.locator('#playBtn').click();assert.equal(await q.locator('#handsLeft').textContent(),'3');await c.close();});
 await check('Consola y recursos: cero errores',async()=>assert.deepEqual(errors,[]));
}finally{
 fs.writeFileSync(path.join(evidence,'browser-results.json'),JSON.stringify({browser:browser.version(),date:new Date().toISOString(),results,errors},null,2));
 await browser.close();await new Promise(r=>server.close(r));
}
