import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const render=read('../js/ui/render.js'),app=read('../js/app.js'),sw=read('../sw.js');
const bossIds=['blind-astronomer','abyssal-mother','faceless-king','devourer','sleeper','mirror-saint','black-choir','the-gate'];
const sceneIds=['route-map','drowned-market','nameless-altar','wall-less-door','beyond-the-gate','the-last-signal','tide-refuge'];
for(const id of bossIds)assert.ok(fs.existsSync(new URL(`../assets/art/entities/${id}.svg`,import.meta.url)),`portrait missing: ${id}`);
for(const id of sceneIds)assert.ok(fs.existsSync(new URL(`../assets/art/scenes/${id}.svg`,import.meta.url)),`scene missing: ${id}`);
const mapBody=render.match(/const BOSS_ART=\{([^}]+)\};/)?.[1]||'';
const bossMap=Object.fromEntries([...mapBody.matchAll(/'([^']+)':'([^']+)'/g)].map(([,id,file])=>[id,file]));
assert.deepEqual(bossIds.map(id=>bossMap[id]),bossIds,'each boss must have its own portrait');
assert.match(render,/BOSS_ART\[zone\.boss\.id\].*\.svg/);
assert.match(render,/state\.status==='lost'/);
assert.match(render,/makeButton\('INTENTAR DE NUEVO','restart'\)/);
assert.match(render,/makeButton\('NUEVA EXPEDICIÓN','restart'\)/);
assert.match(app,/else if\(a==='restart'\)startNewExpedition\(\)/);
assert.match(app,/abyssal-quick-guide-seen-rc7/);
assert.match(app,/updateAppBtn\.addEventListener/);
for(const id of [...bossIds,...sceneIds])assert.ok(sw.includes(`${id}.svg`),`offline cache missing: ${id}`);
console.log(`EXPERIENCE TESTS: ${bossIds.length} distinct bosses + ${sceneIds.length} scenes + guide/end-run flows/offline cache PASS`);
