import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const index=read('../index.html'),app=read('../js/app.js'),render=read('../js/ui/render.js'),css=read('../css/core.css'),sw=read('../sw.js');
let n=0;const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
t('sin handlers inline',()=>assert.doesNotMatch(index,/\son(?:click|change|load|error)\s*=/i));
t('sin innerHTML inseguro',()=>assert.doesNotMatch(app+render,/\binnerHTML\b|insertAdjacentHTML|document\.write/));
t('sin eval dinámico',()=>assert.doesNotMatch(app+render,/\beval\s*\(|new Function\s*\(/));
t('frontend sin URLs externas',()=>assert.doesNotMatch(index+app+render+sw,/https?:\/\//i));
t('rutas de app relativas',()=>assert.doesNotMatch(index+app+render+sw,/[\"']\/(?!\/)/));
t('ritual renderizado como botón',()=>assert.match(render,/interactive\?'button':'article'/));
t('barra locura es progressbar',()=>assert.match(index,/id="madnessTrack"[^>]*role="progressbar"[^>]*aria-valuemin="0"[^>]*aria-valuemax="100"/));
t('locura actualiza aria-valuenow',()=>assert.match(render,/aria-valuenow/));
t('foco visible explícito',()=>assert.match(css,/:focus-visible/));
t('importación limitada a 2 MB',()=>assert.match(app,/file\.size>2_000_000/));
t('input de save restringe JSON',()=>assert.match(index,/accept="application\/json,\.json"/));
t('Service Worker limita mismo origen',()=>assert.match(sw,/url\.origin!==self\.location\.origin/));
t('entrypoint clásico portable',()=>{assert.ok(index.includes('js/app.bundle.js?v=1.0.0-rc.10'));assert.doesNotMatch(index,/type="module"/);});
t('guía accesible con apertura inicial recordada',()=>{assert.match(index,/<details class="quick-guide">/);assert.match(index,/Puntuación:/);assert.match(index,/Alcanza el objetivo/);assert.match(app,/quickGuide\.open=true/);assert.match(app,/abyssal-quick-guide-seen-rc7/);});
console.log(`HARDENING TESTS: ${n}/14 PASS`);
