import assert from 'node:assert/strict';
import { newRun, toggleCard, playSelection, claimReward, chooseRoute } from '../js/core/game.js';
import { targetForEncounter, makeRouteOptions, rewardForEncounter, advanceEncounter } from '../js/gameplay/progression.js';
import { buyItem, acceptPact, resolveEvent, resolveSanctuary, resolveCache, continueFromNode, useRitual } from '../js/gameplay/meta.js';

const fixed=()=>0.123456;
assert.equal(targetForEncounter(1),300);
assert.equal(targetForEncounter(3),334);
assert.equal(targetForEncounter(4),421);
assert.equal(targetForEncounter(32),992);
assert.equal(targetForEncounter(3,1),743);
let state=newRun(fixed);
assert.equal(makeRouteOptions(state).length,4);
for(let zone=0;zone<8;zone++){
  for(let battleInZone=1;battleInZone<=(zone===7?3:4);battleInZone++){const run=newRun('ROUTE-CHECK');run.encounter=zone*4+battleInZone;const options=makeRouteOptions(run);assert.ok(options.some(x=>x.type==='battle'));assert.ok(options.some(x=>x.type==='sanctuary'));assert.equal(options.length,4);assert.equal(new Set(options.map(x=>x.type)).size,4);if(battleInZone===1||battleInZone===3)assert.ok(options.some(x=>x.type==='event'));}
}
const legacy=newRun('LEGACY-ROUTE');legacy.campaignVersion=1;legacy.encounter=1;assert.deepEqual(makeRouteOptions(legacy).map(x=>x.type),['battle','shop','event','sanctuary']);
assert.equal(rewardForEncounter(state),11);
state.totalScore=299;
toggleCard(state,state.hand[0].id);
const win=playSelection(state);
assert.equal(win.ok,true);
assert.equal(state.screenMode,'reward');
assert.equal(state.status,'choice');
const before=state.echoes;
assert.equal(claimReward(state).ok,true);
assert.ok(state.echoes>before);
assert.equal(state.screenMode,'route');
const shop=state.routeOptions.find(n=>n.type==='shop');
assert.ok(shop);
assert.equal(chooseRoute(state,shop.id).ok,true);
assert.equal(state.screenMode,'shop');
state.echoes=50;
assert.equal(buyItem(state,'salt-circle').ok,true);
assert.equal(state.rituals.length,1);
state.madness=40;
assert.equal(useRitual(state,'salt-circle').ok,true);
assert.equal(state.madness,22);
assert.equal(acceptPact(state,'blood-pact').ok,true);
assert.equal(state.pacts[0].id,'blood-pact');
state.screenMode='event'; state.status='choice'; state.currentNode={eventId:'silent-bell'}; const echoes=state.echoes;
assert.equal(resolveEvent(state,'hear').ok,true); assert.ok(state.echoes>echoes); assert.ok(state.madness>=34);
const cacheRun=newRun('CACHE');cacheRun.screenMode='cache';cacheRun.madness=20;assert.equal(resolveCache(cacheRun,'gather').ok,true);assert.equal(cacheRun.echoes,24);assert.equal(cacheRun.madness,30);assert.equal(resolveCache(cacheRun,'unknown').ok,false);
const oldEncounter=state.encounter;
assert.equal(continueFromNode(state).ok,true);
assert.equal(state.encounter,oldEncounter+1);
assert.equal(state.screenMode,'battle');
state.screenMode='sanctuary';state.madness=40;const rest=resolveSanctuary(state,'rest');assert.equal(rest.ok,true);assert.equal(state.madness,22);
state.screenMode='sanctuary';state.echoes=0;state.madness=10;const bargain=resolveSanctuary(state,'bargain');assert.equal(bargain.ok,true);assert.equal(state.echoes,20);assert.equal(state.madness,18);
state.screenMode='sanctuary';state.hand[0].corruption=2;assert.equal(resolveSanctuary(state,'purify').ok,true);assert.equal(state.hand[0].corruption,1);
const relicRun=newRun(fixed);relicRun.relics.push({id:'coral-heart'},{id:'ink-compass'});advanceEncounter(relicRun);assert.equal(relicRun.handsLeft,5);assert.equal(relicRun.discardsLeft,6);
relicRun.encounter=2;relicRun.screenMode='reward';relicRun.status='choice';relicRun.pendingReward=10;relicRun.relics.push({id:'waking-seal'});relicRun.madness=30;claimReward(relicRun);assert.equal(relicRun.madness,24);
console.log('PASS: progresión, rutas, eventos y refugios');
