import assert from 'node:assert/strict';
import { newRun, toggleCard, playSelection, claimReward, chooseRoute } from '../js/core/game.js';
import { targetForEncounter, makeRouteOptions, rewardForEncounter } from '../js/gameplay/progression.js';
import { buyItem, acceptPact, resolveEvent, continueFromNode, useRitual } from '../js/gameplay/meta.js';

const fixed=()=>0.123456;
assert.equal(targetForEncounter(1),300);
assert.equal(targetForEncounter(3),743);
let state=newRun(fixed);
assert.equal(makeRouteOptions(state).length,3);
assert.equal(rewardForEncounter(state),11);
state.totalScore=299;
toggleCard(state,state.hand[0].id);
const win=playSelection(state);
assert.equal(win.ok,true);
assert.equal(state.screenMode,'reward');
assert.equal(state.status,'choice');
const before=state.echoes;
assert.equal(claimReward(state).ok,true);
assert.ok(state.echoes>before);
assert.equal(state.screenMode,'route');
const shop=state.routeOptions.find(n=>n.type==='shop');
assert.ok(shop);
assert.equal(chooseRoute(state,shop.id).ok,true);
assert.equal(state.screenMode,'shop');
state.echoes=50;
assert.equal(buyItem(state,'salt-circle').ok,true);
assert.equal(state.rituals.length,1);
state.madness=40;
assert.equal(useRitual(state,'salt-circle').ok,true);
assert.equal(state.madness,22);
assert.equal(acceptPact(state,'blood-pact').ok,true);
assert.equal(state.pacts[0].id,'blood-pact');
state.screenMode='event'; state.status='choice'; const echoes=state.echoes;
assert.equal(resolveEvent(state,'open').ok,true); assert.ok(state.echoes>echoes); assert.ok(state.madness>=34);
const oldEncounter=state.encounter;
assert.equal(continueFromNode(state).ok,true);
assert.equal(state.encounter,oldEncounter+1);
assert.equal(state.screenMode,'battle');
console.log('PASS: 20 comprobaciones de progresión/rutas/economía');
