import assert from 'node:assert/strict';
import {newRun,toggleCard,playSelection} from '../js/core/game.js';
import {onBossHandResolved} from '../js/gameplay/bosses.js';
import {serializeRun,restoreRun,saveRun} from '../js/persistence/run-store.js';
import {buyItem} from '../js/gameplay/meta.js';
import {safeStorage} from '../js/persistence/storage.js';
import {pulseEffect} from '../js/ui/effects.js';
const s=newRun('BOSS-SAVE');s.encounter=9;
const card=s.hand[0],oldSuit=card.suit,id=card.id;
onBossHandResolved(s,[card]);assert.notEqual(card.suit,oldSuit);assert.equal(card.id,id);
const restored=restoreRun(serializeRun(s));assert.equal(restored.hand[0].suit,card.suit);
console.log('PASS guardar/restaurar cartas transformadas por Rey Sin Rostro');
s.echoes=100;buyItem(s,'bone-die');const money=s.echoes;
assert.equal(buyItem(s,'bone-die').ok,false);assert.equal(s.echoes,money);
console.log('PASS no cobrar una reliquia duplicada');
const original=Object.getOwnPropertyDescriptor(globalThis,'localStorage');
Object.defineProperty(globalThis,'localStorage',{configurable:true,get(){throw new Error('denied');}});
assert.equal(safeStorage(),null);
if(original)Object.defineProperty(globalThis,'localStorage',original);else delete globalThis.localStorage;
console.log('PASS acceso a localStorage denegado');
const result=await saveRun(s,{indexedDBImpl:null,storage:null});assert.equal(result.ok,false);
console.log('PASS ausencia de storage no declara guardado exitoso');
const store=new Map(),memory={setItem:(k,v)=>store.set(k,v)};
const blocked={open(){const req={};queueMicrotask(()=>{req.result={close(){},transaction(){return {objectStore(){return {put(){return {}}}},abort(){this.onabort?.()}}}};req.onsuccess();});return req;}};
assert.equal((await saveRun(s,{indexedDBImpl:blocked,storage:memory})).backend,'localStorage');
console.log('PASS timeout de transacción IDB con fallback');
const cls=new Set();const body={classList:{add:c=>cls.add(c),remove:c=>cls.delete(c)},offsetWidth:1};
pulseEffect('score',{body,duration:5});pulseEffect('select',{body,duration:5});
await new Promise(r=>setTimeout(r,20));assert.equal(cls.size,0);
console.log('PASS efectos consecutivos no dejan clases persistentes');
