import { zoneForEncounter, battleLabel } from '../gameplay/zones.js';
import { unlockedCodex } from '../meta/codex.js';
import { SHOP_ITEMS, PACTS, EVENTS } from '../economy/content.js';

const refs = {
  table:document.querySelector('.table'), hand: document.querySelector('#hand'), handName: document.querySelector('#handName'), baseScore: document.querySelector('#baseScore'), multiplier: document.querySelector('#multiplier'), previewScore: document.querySelector('#previewScore'), totalScore: document.querySelector('#totalScore'),
  targetScore: document.querySelector('#targetScore'), handsLeft: document.querySelector('#handsLeft'), discardsLeft: document.querySelector('#discardsLeft'), deckCount: document.querySelector('#deckCount'), selectionCount: document.querySelector('#selectionCount'), corruptionCount: document.querySelector('#corruptionCount'),
  playBtn: document.querySelector('#playBtn'), discardBtn: document.querySelector('#discardBtn'), message: document.querySelector('#message'), madnessValue: document.querySelector('#madnessValue'), madnessBar: document.querySelector('#madnessBar'), madnessTrack: document.querySelector('#madnessTrack'),
  encounter: document.querySelector('#encounterValue'), echoes: document.querySelector('#echoesValue'), nodePanel: document.querySelector('#nodePanel'), powers: document.querySelector('#powers'),
  sectorEyebrow:document.querySelector('#sectorEyebrow'),sectorSubtitle:document.querySelector('#sectorSubtitle'),threatBanner:document.querySelector('#threatBanner'),seedValue:document.querySelector('#seedValue'),metaStats:document.querySelector('#metaStats'),codexList:document.querySelector('#codexList')
};
const RANK_MOTIFS={'2':'·✦\n✦·','3':'✦·✦\n · ','4':'✦ ✦\n✦ ✦','5':'✦ ✦\n ✦ \n✦ ✦','6':'✦ ✦\n✦ ✦\n✦ ✦','7':'✦·✦\n ✦ \n✦·✦','8':'✦✦\n◈\n✦✦','9':'✦✦✦\n◉\n✦✦✦','10':'✦◈✦\n◈◉◈\n✦◈✦','J':'╱╲\n◉\n╲╱','Q':'╔◉╗\n╚╦╝\n ║ ','K':'♜\n◉\n╱╲','A':'✦\n◉\n✦'};
const SUIT_SIGILS={spade:'✦',heart:'♥',diamond:'◉',club:'Ψ'};
const SECTOR_ART={'drowned-port':'drowned-port-wide.png','sunken-library':'sunken-library.webp','moonless-forest':'moonless-forest.webp','black-observatory':'black-observatory.webp','impossible-city':'impossible-city.png','ash-sea':'ash-sea.png','abyssal-temple':'abyssal-temple.png','beyond-gate':'beyond-gate.png'};
const BOSS_ART={'blind-astronomer':'blind-astronomer','abyssal-mother':'abyssal-mother','faceless-king':'faceless-king','devourer':'devourer','sleeper':'sleeper','mirror-saint':'mirror-saint','black-choir':'black-choir','the-gate':'the-gate'};
const NODE_ART={route:'route-map',shop:'drowned-market',ritual:'nameless-altar',event:'wall-less-door',sanctuary:'tide-refuge',victory:'beyond-the-gate',lost:'the-last-signal'};
const make=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text!=null)el.textContent=text;return el;};
function makeButton(text, action, value, cls='node-btn'){const b=make('button',cls,text);b.type='button';b.dataset.action=action;if(value)b.dataset.value=value;return b;}
function renderCard(card,selected,onToggle){const btn=make('button',`card suit-${card.suit} corrupt-${card.corruption||0}${selected?' selected':''}`);btn.type='button';btn.dataset.cardId=card.id;btn.dataset.rank=String(card.rank);btn.setAttribute('aria-pressed',String(selected));btn.setAttribute('aria-label',`${card.rankLabel} de ${card.suitName}${card.corruption?`, corrupción ${card.corruption}`:''}`);const top=make('div','card-top');top.append(make('span','rank',card.rankLabel),make('span','suit-mini',SUIT_SIGILS[card.suit]));const motif=make('span','motif',`${SUIT_SIGILS[card.suit]}${RANK_MOTIFS[card.rankLabel]}${SUIT_SIGILS[card.suit]}`);const bottom=make('div','card-bottom');bottom.append(make('span','name',card.suitName.toUpperCase()),make('span','corruption-pips',card.corruption?'◆'.repeat(card.corruption):'···'));btn.append(top,motif,bottom);btn.addEventListener('click',()=>onToggle(card.id));return btn;}
function powerChip(kind,icon,title,text){const interactive=kind==='ritual';const a=make(interactive?'button':'article',`power-chip ${kind}`);if(interactive){a.type='button';a.setAttribute('aria-label',`Usar ritual: ${title}. ${text}`);}a.append(make('span','power-icon',icon));const d=make('div');d.append(make('b','',title),make('small','',text));a.append(d);return a;}
function renderPowers(state){refs.powers.replaceChildren();refs.powers.append(powerChip('entity','◉','EL OJO QUE NO DUERME','3+ Ojos: +1 Resonancia · cada mano +1 Locura'));const relicText={'salt-lamp':'+1 descarte por encuentro.','bone-die':'+12 Ecos al superar un encuentro.','coral-heart':'+1 mano por encuentro.','ink-compass':'+1 descarte por encuentro.','waking-seal':'−6 Locura al vencer élites y jefes.'};for(const relic of state.relics)refs.powers.append(powerChip('relic','✦',relic.name,relicText[relic.id]||'Objeto persistente de la expedición.'));for(const pact of state.pacts)refs.powers.append(powerChip('pact','⚠',pact.name,'Poder alto a cambio de una consecuencia.'));for(const ritual of state.rituals){const chip=powerChip('ritual','✧',ritual.name,'Ritual consumible disponible.');chip.dataset.ritualId=ritual.id;refs.powers.append(chip);}}
function renderNode(state){refs.nodePanel.replaceChildren();refs.nodePanel.hidden=state.screenMode==='battle'&&state.status!=='lost';if(refs.nodePanel.hidden)return;const title=make('h2','node-title','');const text=make('p','node-copy','');const actions=make('div','node-actions');let scene=state.status==='lost'?'lost':state.screenMode;
  if(state.status==='lost'){title.textContent='LA EXPEDICIÓN SE HUNDE';title.classList.add('defeat-mark');text.textContent='La Locura ha devorado la última mano. Los Ecos que reuniste quedan en el Códice.';actions.append(makeButton('INTENTAR DE NUEVO','restart'));}
  if(state.screenMode==='reward'){title.textContent='UMBRAL SUPERADO';text.textContent=`La oscuridad ofrece ${state.pendingReward} Ecos antes de mostrar la siguiente senda.`;actions.append(makeButton(`RECOGER ${state.pendingReward} ECOS`,'claim'));}
  if(state.screenMode==='route'){scene='route';title.textContent='ELIGE LA SENDA';text.textContent='Cada decisión cambia lo que llevas al siguiente combate.';for(const node of state.routeOptions){const card=make('div','offer route-offer');card.append(make('b','',`${node.icon} ${node.name}`),make('small','',node.description||({battle:'Arriesga una batalla para avanzar y cobrar Ecos.',shop:'Compra una ventaja con los Ecos que conservas.',ritual:'Acepta un pacto poderoso con un precio permanente.'}[node.type]||'Investiga una senda desconocida.')));card.append(makeButton('ELEGIR','route',node.id,'mini-btn'));actions.append(card);}}
  if(state.screenMode==='shop'){scene='shop';title.textContent='MERCADO SUMERGIDO';text.textContent=`Ecos disponibles: ${state.echoes}`;for(const item of SHOP_ITEMS){const card=make('div','offer');card.append(make('b','',`${item.name} · ${item.cost}E`),make('small','',item.text),makeButton('COMPRAR','buy',item.id,'mini-btn'));actions.append(card);}actions.append(makeButton('ABANDONAR MERCADO','continue'));}
  if(state.screenMode==='ritual'){scene='ritual';title.textContent='ALTAR SIN NOMBRE';text.textContent='Solo un pacto puede arraigar en este altar.';for(const pact of PACTS){const card=make('div','offer');card.append(make('b','',pact.name),make('small','',pact.text),makeButton('ACEPTAR','pact',pact.id,'mini-btn'));actions.append(card);}actions.append(makeButton('RECHAZAR Y SEGUIR','continue'));}
  if(state.screenMode==='event'){scene='event';if(state.campaignVersion<2){title.textContent='LA PUERTA SIN MURO';text.textContent='Del otro lado llega el sonido de cartas barajándose bajo el agua.';actions.append(makeButton('ABRIR · +12 LOCURA','event','open'),makeButton('IGNORAR · −5 LOCURA','event','ignore'));}else{const story=EVENTS.find(e=>e.id===state.currentNode?.eventId)||EVENTS[0];title.textContent=story.name;text.textContent=story.text;for(const choice of story.choices)actions.append(makeButton(choice.label,'event',choice.id));}}
  if(state.screenMode==='sanctuary'){scene='sanctuary';title.textContent='REFUGIO ENTRE MAREAS';text.textContent='La piedra mantiene fuera al océano durante unos minutos. Elige qué quieres recuperar.';actions.append(makeButton('DESCANSAR · −18 LOCURA','sanctuary','rest'),makeButton('PURIFICAR · −1 CORRUPCIÓN','sanctuary','purify'),makeButton('HACER UN TRATO · +20 ECOS · +8 LOCURA','sanctuary','bargain'));}
  if(state.screenMode==='victory'){scene='victory';title.textContent='LA PUERTA CEDE';title.classList.add('victory-mark');text.textContent=`Has atravesado los 8 sectores y derrotado ${state.bossesDefeated} entidades. La expedición ha terminado.`;actions.append(makeButton('NUEVA EXPEDICIÓN','restart'));}
  const art=make('img',`node-art${scene==='victory'?' victory-art':''}`);art.src=`./assets/art/scenes/${NODE_ART[scene]||'route-map'}.svg`;art.alt='';art.setAttribute('aria-hidden','true');
  refs.nodePanel.append(title,text,art,actions);
}
export function render(state,preview,onToggle){const zone=zoneForEncounter(state.encounter,state.campaignVersion);document.body.dataset.zone=zone.id;document.body.dataset.danger=zone.isBoss?'boss':zone.isElite?'elite':'normal';document.body.dataset.madness=state.madness>=100?'rupture':state.madness>=75?'fracture':state.madness>=50?'distortion':state.madness>=25?'whispers':'stable';refs.sectorEyebrow.textContent=`SECTOR ${zone.zoneIndex+1} · ${zone.name}`;refs.sectorSubtitle.textContent=zone.subtitle;refs.threatBanner.hidden=!(zone.isBoss||zone.isElite);refs.threatBanner.textContent=zone.isBoss?`${battleLabel(state.encounter,state.campaignVersion)} · ${zone.boss.rule}`:`ÉLITE · UMBRAL REFORZADO · +1 LOCURA POR MANO`;refs.table?.style?.setProperty('--sector-image',`url("${new URL(`./assets/art/sectors/${SECTOR_ART[zone.id]||'black-observatory'}`,document.baseURI).href}")`);refs.threatBanner.replaceChildren();if(zone.isBoss){const bossArt=make('img','boss-portrait');bossArt.src=`./assets/art/entities/${BOSS_ART[zone.boss.id]||'blind-astronomer'}.svg`;bossArt.alt=zone.boss.name;refs.threatBanner.append(bossArt,make('span','',`${battleLabel(state.encounter,state.campaignVersion)} · ${zone.boss.rule}`));}else refs.threatBanner.textContent=`ÉLITE · UMBRAL REFORZADO · +1 LOCURA POR MANO`;refs.hand.replaceChildren();for(const card of state.hand)refs.hand.appendChild(renderCard(card,state.selectedIds.has(card.id),onToggle));refs.handName.textContent=preview?.name??'—';refs.baseScore.textContent=preview?.base??0;refs.multiplier.textContent=preview?`×${preview.mult}`:'×0';refs.previewScore.textContent=preview?.score??0;refs.totalScore.textContent=state.totalScore;refs.targetScore.textContent=state.targetScore;refs.handsLeft.textContent=state.handsLeft;refs.discardsLeft.textContent=state.discardsLeft;refs.deckCount.textContent=`MAZO: ${state.deck.length} · DESCARTE: ${state.discardPile.length}`;refs.selectionCount.textContent=`SELECCIONADAS: ${state.selectedIds.size}/5`;refs.corruptionCount.textContent=`CORRUPCIÓN: ${state.hand.reduce((n,c)=>n+(c.corruption||0),0)}`;refs.madnessValue.textContent=`${state.madness}%`;refs.madnessBar.style.width=`${state.madness}%`;refs.madnessTrack?.setAttribute('aria-valuenow',String(state.madness));refs.encounter.textContent=state.encounter;refs.echoes.textContent=state.echoes;if(refs.seedValue)refs.seedValue.textContent=state.seed;const battle=state.screenMode==='battle'&&state.status==='playing';refs.playBtn.disabled=!battle||state.selectedIds.size===0||state.handsLeft<=0;refs.discardBtn.disabled=!battle||state.selectedIds.size===0||state.discardsLeft<=0;renderPowers(state);renderNode(state);}
export function setMessage(text){refs.message.textContent=text;}

export function renderMetaPanel(meta,state){if(!refs.metaStats||!refs.codexList)return;refs.metaStats.replaceChildren();const stats=[['FRAGMENTOS',meta.fragments],['RUNS',meta.runs],['VICTORIAS',meta.wins],['MEJOR ENCUENTRO',meta.bestEncounter],['MEJOR PUNTUACIÓN',meta.bestScore],['MANOS TOTALES',meta.totalHands]];for(const [k,v] of stats){const d=make('div','meta-stat');d.append(make('span','',k),make('strong','',String(v)));refs.metaStats.append(d);}refs.codexList.replaceChildren();for(const e of unlockedCodex(meta)){const a=make('article',`codex-entry ${e.unlocked?'unlocked':'locked'}`);a.append(make('small','',e.kind),make('b','',e.unlocked?e.name:'████████'),make('p','',e.unlocked?e.text:'Entrada no descubierta.'));refs.codexList.append(a);}}
