// Dependency-free packer for this project's named local ES modules.
// Intentionally rejects unsupported imports/exports instead of emitting a partial build.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const modules=new Map(),visiting=new Set(),chunks=[];
function visit(file){
 if(modules.has(file))return modules.get(file);
 if(visiting.has(file))throw new Error('Circular import: '+file);
 visiting.add(file);let code=fs.readFileSync(file,'utf8');
 code=code.replace(/^import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"];?\s*$/gm,(_,names,ref)=>{
  if(!ref.startsWith('.'))throw new Error('External dependency: '+ref);
  const id=visit(path.resolve(path.dirname(file),ref));
  return `const {${names.replace(/\s+as\s+/g,':')}}=${id};`;
 });
 const exports=[];code=code.replace(/\bexport\s+(?=(?:async\s+)?function\s|const\s|let\s|class\s)/g,'');
 const original=fs.readFileSync(file,'utf8');
 for(const m of original.matchAll(/\bexport\s+(?:async\s+)?(?:function|const|let|class)\s+(\w+)/g))exports.push(m[1]);
 if(/^\s*(import|export)\b/m.test(code))throw new Error('Unsupported module syntax: '+file);
 const id='m'+modules.size;modules.set(file,id);visiting.delete(file);
 chunks.push(`// ${path.relative(root,file)}\nconst ${id}=(()=>{\n${code}\nreturn {${exports.join(',')}};\n})();`);return id;
}
visit(path.join(root,'js/app.js'));
fs.writeFileSync(path.join(root,'js/app.bundle.js'),`/* Generated by node scripts/build.mjs. */\n(()=>{'use strict';\n${chunks.join('\n')}\n})();\n`);
console.log('Packed',modules.size,'local modules → js/app.bundle.js');
